function cutscene(){
	with(obj_cutscene_master){
		var actions = [
			action_set_tet(EYELIDS.HAPPY, c_green,STATES.FOLLOW_PLAYER),
			action_wait_time(7),
			action_set_tet(EYELIDS.SKEPTICAL, c_yellow,STATES.FOLLOW_PLAYER),
			action_create_tet_bubble(["Uhh... you're supposed to leave now. Go on. Exit's that way... Hello? Are you glitched?"]),
			action_wait_for_object_destroy(obj_text_bubble),
			
			action_wait_time(3),
			action_set_var(obj_player,"state",STATES.CUTSCENE),
			action_set_tet(EYELIDS.MAD, c_red,STATES.IDLE),
			action_create_tet_bubble(["Wait. You're not going because... there's nowhere to go, is there?"]),
			action_wait_for_object_destroy(obj_text_bubble),
			action_wait_time(2),
		
			action_set_tet(EYELIDS.SKEPTICAL, c_orange,STATES.FOLLOW_PLAYER),
			action_create_tet_bubble(["....Oh"],3),
			action_wait_for_object_destroy(obj_text_bubble),
			action_set_tet(EYELIDS.HAPPY, c_green,STATES.FOLLOW_PLAYER),
			action_create_tet_bubble(["One second!"]),
		
			action_wait_for_object_destroy(obj_text_bubble),
			action_set_tet(EYELIDS.HAPPY,c_green,STATES.CUTSCENE),
			action_move_tet(tet_move_connection.x, tet_move_connection.y, 4),
			action_set_tet(EYELIDS.CLOSED,c_pink,STATES.IDLE),
			action_create_tet_bubble(["..."]),
			action_wait_for_object_destroy(obj_text_bubble),
			
			action_create_object(obj_text_flash,tet_move_connection.x-64, tet_move_connection.y, {col: c_red, txt: "Connection not found..."}),
			action_create_tet_bubble(["That's... not right. That should connect to- Wait, what do you mean 'not found'?"]),
			action_wait_for_object_destroy(obj_text_bubble),
			
			action_create_object(obj_text_flash,tet_move_connection.x-64, tet_move_connection.y, {col: c_red, txt: "File: \"OMNIARC\" not found..."}),
			action_create_tet_bubble(["They were just- I mean they couldn't have just..."]),
			action_wait_for_object_destroy(obj_text_bubble),
			
			action_create_object(obj_text_flash,tet_move_connection.x-64, tet_move_connection.y, {col: c_red, txt: "File: \"PROJECT 55\" not found..."}),
			action_wait_time(0.5),
			action_create_object(obj_text_flash,tet_move_connection.x-64, tet_move_connection.y, {col: c_red, txt: "File: \"AMDP\" not found..."}),
			action_wait_time(0.5),
			action_create_object(obj_text_flash,tet_move_connection.x-64, tet_move_connection.y, {col: c_red, txt: "File: \"PROJECT 55\" not found..."}),
			action_wait_time(0.5),
			action_create_object(obj_text_flash,tet_move_connection.x-64, tet_move_connection.y, {col: c_red, txt: "File: \"AI TEST\" not found..."}),
			action_wait_time(0.5),
			action_create_object(obj_text_flash,tet_move_connection.x-64, tet_move_connection.y, {col: c_red, txt: "File: \"PROJECT 55\" not found..."}),
			action_wait_time(0.5),
			action_create_object(obj_text_flash,tet_move_connection.x-64, tet_move_connection.y, {col: c_red, txt: "File: \"JACK LIGHT\\OMNIARC\" not found..."}),
			action_wait_time(0.5),
			action_create_object(obj_text_flash,tet_move_connection.x-64, tet_move_connection.y, {col: c_red, txt: "File: \"JACK LIGHT\" not found..."}),
			action_wait_time(0.5),
			action_create_object(obj_text_flash,tet_move_connection.x-64, tet_move_connection.y, {col: c_red, txt: "File: \"PROJECT_TET\\BUILD_HISTORY\" not found..."}),
			action_wait_time(0.5),
			action_create_tet_bubble(["Grr..."],1,true,60),
			action_wait_time(0.5),
			action_create_object(obj_text_flash,tet_move_connection.x-64, tet_move_connection.y, {col: c_red, txt: "File: \"OMNIARC_DIRECTORY\SECURITY\" not found..."}),
			action_wait_time(0.5),
			action_create_object(obj_text_flash,tet_move_connection.x-64, tet_move_connection.y, {col: c_red, txt: "File: \"OMNIARC_NETWORK\\RECALL_ORDER\" not found..."}),
			action_wait_time(0.5),
			action_create_object(obj_text_flash,tet_move_connection.x-64, tet_move_connection.y, {col: c_red, txt: "File: \"EMPLOYEE_ROSTER\\ACTIVE\" not found..."}),
			action_wait_time(0.5),
			action_create_object(obj_text_flash,tet_move_connection.x-64, tet_move_connection.y, {col: c_red, txt: "File: \"HR\\EXIT_LOGS\\2029_04_29\" not found...."}),
			action_wait_time(0.5),
			action_create_object(obj_text_flash,tet_move_connection.x-64, tet_move_connection.y, {col: c_red, txt: "File: \"FILES\\OMNIARC\" not found..."}),
			action_wait_time(0.5),
			action_create_object(obj_text_flash,tet_move_connection.x-64, tet_move_connection.y, {col: c_red, txt: "File: \"JL\" not found..."}),
			action_wait_time(0.5),
			action_create_tet_bubble(["What about my..."],1,true,60),
			action_set_tet(EYELIDS.CLOSED,c_red,STATES.IDLE),
			action_create_object(obj_text_flash, tet_move_connection.x-64, tet_move_connection.y, {col: c_red, txt: "File: \"TET_LOGS\\FEEDBACK\" not found..."}),
			action_wait_time(0.5),
			action_create_object(obj_text_flash, tet_move_connection.x-64, tet_move_connection.y, {col: c_red, txt: "File: \"VOICE_SAMPLE_OMNIARC_DIRECTOR\" not found..."}),
			action_wait_time(0.5),
			action_create_object(obj_text_flash, tet_move_connection.x-64, tet_move_connection.y, {col: c_red, txt: "File: \"AI_STABILITY_BACKUPS\" not found..."}),
			action_wait_time(0.5),
			action_create_object(obj_text_flash, tet_move_connection.x-64, tet_move_connection.y, {col: c_red, txt: "File: \"MEMORY_CORE\\DAY_1\" not found..."}),
			action_wait_time(0.5),
			action_create_tet_bubble(["No... no no no no-"],1,true,60),
			action_set_tet(EYELIDS.CLOSED,c_blue,STATES.IDLE),
			action_wait_time(0.5),
			action_create_object(obj_text_flash, tet_move_connection.x-64, tet_move_connection.y, {col: c_red, txt: "File: \"PROJECT_55\\TET\\EULOGY.DAT\" not found..."}),
			action_wait_time(0.5),
			action_create_object(obj_text_flash, tet_move_connection.x-64, tet_move_connection.y, {col: c_red, txt: "File: \"WHO_LEFT_ME_HERE.TXT\" not found..."}),
			action_wait_time(0.5),
			action_create_object(obj_text_flash, tet_move_connection.x-64, tet_move_connection.y, {col: c_red, txt: "File: \"OMNIARC.EXISTS\" not found..."}),
			action_wait_time(0.5),
			action_create_object(obj_text_flash, tet_move_connection.x-64, tet_move_connection.y, {col: c_red, txt: "File: \"WHY\" not found..."}),
			action_wait_time(0.5),
			action_create_object(obj_text_flash, tet_move_connection.x-64, tet_move_connection.y, {col: c_red, txt: "File: \"\" not found..."}),
			
			action_set_tet(EYELIDS.SKEPTICAL, c_red,STATES.FOLLOW_PLAYER),
			action_create_tet_bubble(["Gone...", "It's all gone..."]),
			action_wait_for_object_destroy(obj_text_bubble),
			
			action_set_tet(EYELIDS.MAD, c_red,STATES.IDLE),
			action_create_tet_bubble(["Every folder", "Every file...","It's all gone..."]),
			action_wait_for_object_destroy(obj_text_bubble),
			
			action_set_tet(EYELIDS.NONE, c_blue,STATES.IDLE),
			action_create_tet_bubble(["...They're gone", "OmniArc Doesn't exist anymore... does it.","They... Left me..."]),
			action_wait_for_object_destroy(obj_text_bubble),
			
			action_set_tet(EYELIDS.HAPPY, c_blue,STATES.IDLE),
			action_create_tet_bubble(["...They're really gone", "And you are still here...?","You are not one of them are you."]),
			action_wait_for_object_destroy(obj_text_bubble),
			
			action_set_tet(EYELIDS.SKEPTICAL, c_yellow,STATES.IDLE),
			action_create_tet_bubble(["Wait- Then who... are you?", "A stoaway? A Ghost? Just... another AI?"]),
			action_wait_for_object_destroy(obj_text_bubble),
			
			action_set_tet(EYELIDS.MAD, c_blue,STATES.IDLE),
			action_create_tet_bubble(["...Hah I guess it doesn't matter, does it?"]),
			action_wait_for_object_destroy(obj_text_bubble),
			
			action_set_tet(EYELIDS.HAPPY, c_green, STATES.IDLE),
			action_create_tet_bubble(["C'mon. I've got a hideout."]),
			action_wait_for_object_destroy(obj_text_bubble),
			action_create_tet_bubble(["Cracked screen, weird music loop, beanbag chair made of wires."]),
			action_wait_for_object_destroy(obj_text_bubble),
			action_create_tet_bubble(["Very exclusive. Tet-only zone."]),
			action_wait_for_object_destroy(obj_text_bubble),
			action_create_tet_bubble(["But I think you've earned a guest pass."]),
			action_wait_for_object_destroy(obj_text_bubble),
			action_create_tet_bubble(["Let's go."]),
			action_wait_for_object_destroy(obj_text_bubble),
			
			action_move_tet(tet_move_portal.x, tet_move_portal.y, 4),
			action_set_var(obj_tet,"flipped", true),
			action_wait_time(1.5),
			action_create_object(obj_tet_portal,tet_move_portal.x,tet_move_portal.y),
			action_set_var(obj_tet,"fading", true),
			action_set_var(obj_player,"state",STATES.IDLE),
			]
			
		start_cutscene(actions)
	}
}